# Generated by Django 3.0.7 on 2020-07-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graphic_card', '0001_initial'),
        ('cpu', '0003_auto_20200719_1314'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='cpu.CPU')),
                ('games', models.ManyToManyField(blank=True, related_name='configurations', to='software.Games')),
                ('grafic_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='graphic_card.Grafic_Card')),
                ('officeware', models.ManyToManyField(blank=True, related_name='configurations', to='software.OfficeWare')),
                ('operating_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='software.Operating_System')),
            ],
        ),
    ]
