# Generated by Django 3.0.7 on 2020-07-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_configurator_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurator',
            old_name='officeware',
            new_name='officewares',
        ),
    ]
