# Generated by Django 3.0.7 on 2020-07-20 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_auto_20200719_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurator',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configurator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
