# Generated by Django 3.0.7 on 2020-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='manufacturer',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(max_length=256),
        ),
    ]
