# Generated by Django 3.0.7 on 2020-07-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpu', '0002_auto_20200719_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to=settings.AUTH_USER_MODEL),
        ),
    ]
