# Generated by Django 3.0.7 on 2020-07-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_remove_games_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeware',
            name='price',
        ),
    ]
