# Generated by Django 3.0.7 on 2020-07-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_remove_officeware_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operating_system',
            name='price',
        ),
    ]
