# Generated by Django 3.0.7 on 2020-07-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_remove_operating_system_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='priece',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='officeware',
            old_name='priece',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='operating_system',
            old_name='priece',
            new_name='price',
        ),
    ]
