# Generated by Django 3.0.3 on 2020-07-29 09:45

from django.db import migrations, models
import software.models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_games_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, default='default_game.jpg', null=True, upload_to=software.models.recipe_image_file_path),
        ),
    ]
